[package]
name = "nexus"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2.0.4"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
ethers-signers = "2.0.0"
web3 = "0.18.0"
clap = "2.33.3"
tokio = { version = "1.15.0", features = ["full"] }
