/*
 * 1inch Aggregation protocol API
 *
 *  <h2>Ethereum Network</h2> Using 1inch Aggregation protocol API, you can find the best route to exchange assets and make the exchange. <br><br> Step by step: 1. Lookup addresses of tokens you want to swap, for example ‘0xxx’ , ‘0xxxx’ for DAI -> 1INCH 2. Check for allowance of 1inch router contract to spend source asset (/approve/allowance) 3. If necessary, give approval for 1inch router to spend source token (/approve/transaction) 4. Monitor the best exchange route using (/quote) 5. When you ready use to perform swap (/swap)  
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SwapErrorDto {
    /// HTTP code
    #[serde(rename = "statusCode")]
    pub status_code: f32,
    /// Error code description
    #[serde(rename = "error")]
    pub error: String,
    /// Error description (one of the following)
    #[serde(rename = "description")]
    pub description: String,
    /// Request id
    #[serde(rename = "requestId")]
    pub request_id: String,
    /// Meta information
    #[serde(rename = "meta")]
    pub meta: Vec<crate::models::NestErrorMeta>,
}

impl SwapErrorDto {
    pub fn new(status_code: f32, error: String, description: String, request_id: String, meta: Vec<crate::models::NestErrorMeta>) -> SwapErrorDto {
        SwapErrorDto {
            status_code,
            error,
            description,
            request_id,
            meta,
        }
    }
}


